# Gradle Properties
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

# Mod Properties
version = 1.4.0
maven_group = aqario.equine
archives_base_name = equine

# Fabric Properties
minecraft_version = 26.2
loader_version = 0.19.3

# Fabric API
fabric_api_version = 0.153.0+26.2

# Dependencies
modmenu_version = 20.0.0-beta.4
midnightlib_version = 1.9.3+26.2-fabric